apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: elog-plus-frontend-image
    newName: ghcr.io/eed-web-application/react-ui-demo:sha-82af002
