name: Build and Publish Docker Image
on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-image:
    runs-on: ubuntu-latest

    outputs:
      IMAGE_TO_DEPLOY: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Generate Docker tags based on the following attributes
          tags: |
            type=sha
          labels: |
            maintainer=boogie@slac.stanford.edu

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64/v8
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Start Deployment
    runs-on: ubuntu-latest
    needs: create-image
    steps:
      - run: |
          gh workflow --repo eed-web-application/react-ui-demo-deployment run Deploy -f image="${{needs.create-image.outputs.IMAGE_TO_DEPLOY}}"
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
